// Grammar exercises
const EXERCISES=[
  {topic:"Gusta / Gustan",items:[
    {q:"Me ___ el chocolate.",opts:["gusta","gustan"],ans:0,hint:"singular noun → gusta"},
    {q:"Me ___ los gatos.",opts:["gusta","gustan"],ans:1,hint:"plural noun → gustan"},
    {q:"Me ___ vivir en la ciudad.",opts:["gusta","gustan"],ans:0,hint:"verb → always gusta"},
    {q:"¿Te ___ las películas españolas?",opts:["gusta","gustan"],ans:1,hint:"películas = plural → gustan"},
    {q:"A nosotros nos ___ la playa.",opts:["gusta","gustan"],ans:0,hint:"la playa = singular → gusta"},
    {q:"Me ___ los domingos.",opts:["gusta","gustan"],ans:1,hint:"domingos = plural → gustan"},
    {q:"Me ___ los deportes al aire libre.",opts:["gusta","gustan"],ans:1,hint:"los deportes = plural → gustan"},
    {q:"¿Sabes si a sus amigos les ___ bailar?",opts:["gusta","gustan"],ans:0,hint:"bailar = verb → gusta"},
  ]},
  {topic:"El / La / Los / Las",items:[
    {q:"___ ventana",opts:["el","la"],ans:1,hint:"-a ending → feminine → la"},
    {q:"___ gato",opts:["el","la"],ans:0,hint:"-o ending → masculine → el"},
    {q:"___ libro",opts:["el","la"],ans:0,hint:"-o ending → masculine → el"},
    {q:"___ casa",opts:["el","la"],ans:1,hint:"-a ending → feminine → la"},
    {q:"___ zapato",opts:["el","la"],ans:0,hint:"-o ending → masculine → el"},
    {q:"___ manzana",opts:["el","la"],ans:1,hint:"-a ending → feminine → la"},
    {q:"___ chicos (plural)",opts:["el","los"],ans:1,hint:"masculine plural → los"},
    {q:"___ flores (plural)",opts:["la","las"],ans:1,hint:"feminine plural → las"},
  ]},
  {topic:"Voy a / Quiero / Tengo que",items:[
    {q:"Mañana ___ ir al gimnasio. (planned)",opts:["voy a","quiero","tengo que"],ans:0,hint:"planned future = voy a"},
    {q:"___ descansar. (I want)",opts:["Voy a","Quiero","Tengo que"],ans:1,hint:"desire = quiero"},
    {q:"___ limpiar. (I have to)",opts:["Voy a","Quiero","Tengo que"],ans:2,hint:"obligation = tengo que"},
    {q:"___ viajar a España. (I want)",opts:["Voy a","Quiero","Tengo que"],ans:1,hint:"desire = quiero"},
    {q:"El sábado ___ cocinar. (planned)",opts:["voy a","quiero","tengo que"],ans:0,hint:"planned = voy a"},
    {q:"___ ir al supermercado. (we have to)",opts:["Vamos a","Queremos","Tenemos que"],ans:2,hint:"obligation (we) = tenemos que"},
  ]},
  {topic:"Ser / Estar / Hay",items:[
    {q:"Yo ___ irlandesa. (permanent identity)",opts:["soy","estoy","hay"],ans:0,hint:"permanent identity → ser → soy"},
    {q:"Las llaves ___ encima de la mesa.",opts:["son","están","hay"],ans:1,hint:"location → estar → están"},
    {q:"___ un restaurante cerca. (existence)",opts:["Es","Está","Hay"],ans:2,hint:"existence → hay"},
    {q:"¿Cómo ___ hoy? (temporary state)",opts:["eres","estás","hay"],ans:1,hint:"temporary state → estar → estás"},
    {q:"Mi jefe siempre ___ serio.",opts:["es","está","hay"],ans:1,hint:"temporary/changeable state → estar"},
    {q:"___ muchos gatos en el parque.",opts:["Son","Están","Hay"],ans:2,hint:"existence of things → hay"},
    {q:"España ___ un país muy bonito. (description)",opts:["es","está","hay"],ans:0,hint:"description → ser"},
    {q:"Madrid ___ en el centro de España. (location)",opts:["es","está","hay"],ans:1,hint:"location → estar"},
  ]},
  {topic:"Pretérito perfecto",items:[
    {q:"He ___ la casa. (limpiar)",opts:["limpiado","limpiando","limpié","limpió"],ans:0,hint:"-AR verbs → -ado: limpiado"},
    {q:"¿Qué ___ hecho? (tú)",opts:["he","has","ha","han"],ans:1,hint:"tú → has"},
    {q:"Ella ___ comido en un restaurante.",opts:["ha","he","has","han"],ans:0,hint:"ella → ha"},
    {q:"Nosotros ___ visto una película.",opts:["hemos","habéis","han","he"],ans:0,hint:"nosotros → hemos"},
    {q:"¿Has estado en España ___ vez?",opts:["alguna","ninguna","cada","otra"],ans:0,hint:"alguna vez = ever"},
    {q:"He ___ (ir — irregular)",opts:["ido","voy","ir","va"],ans:0,hint:"ir → ido (irregular)"},
    {q:"He ___ (hacer — irregular)",opts:["hacido","hecho","hacado","haciendo"],ans:1,hint:"hacer → hecho (irregular)"},
    {q:"He ___ (ver — irregular)",opts:["veido","visto","vido","veado"],ans:1,hint:"ver → visto (irregular)"},
  ]},
  {topic:"Mucho / Muy",items:[
    {q:"Tengo ___ dinero. (a lot of — masc.)",opts:["muy","mucho","mucha","muchos"],ans:1,hint:"mucho + masc. singular noun"},
    {q:"Tengo ___ hambre. (a lot of — fem.)",opts:["muy","mucho","mucha","muchas"],ans:2,hint:"mucha + fem. singular noun"},
    {q:"Tengo ___ amigos. (many — masc. pl.)",opts:["muy","mucho","mucha","muchos"],ans:3,hint:"muchos + masc. plural noun"},
    {q:"Hablas ___ bien. (very)",opts:["mucho","muchos","muy","mucha"],ans:2,hint:"muy + adverb — never changes"},
    {q:"Mi hija es ___ inteligente. (very)",opts:["mucho","muchos","muy","mucha"],ans:2,hint:"muy + adjective — never changes"},
    {q:"Mi marido trabaja ___. (a lot — after verb)",opts:["muy","mucho","mucha","muchos"],ans:1,hint:"verb + mucho — never changes"},
  ]},
  {topic:"Saber / Poder",items:[
    {q:"¿___ tocar el piano? — Sí, he estudiado años. (skill)",opts:["Sabes","Puedes"],ans:0,hint:"learned skill → saber"},
    {q:"¿___ tocar el piano? — No, estoy cansada ahora. (circumstance)",opts:["Sabes","Puedes"],ans:1,hint:"circumstances → poder"},
    {q:"¿No ___ conducir? — No, no tengo carné. (no licence)",opts:["sabes","puedes"],ans:0,hint:"no licence = never learned → saber"},
    {q:"¿No ___ conducir? — No, no tengo mis gafas aquí. (no glasses)",opts:["sabes","puedes"],ans:1,hint:"temporary circumstance → poder"},
    {q:"¿___ hablar español? — Un poco. (language skill)",opts:["Sabes","Puedes"],ans:0,hint:"language = learned skill → saber"},
    {q:"¿___ venir mañana? — No, tengo reunión. (availability)",opts:["Sabes","Puedes"],ans:1,hint:"availability → poder"},
  ]},
  {topic:"Colours — agreement",items:[
    {q:"una chaqueta ___ (red)",opts:["rojo","roja","rojos","rojas"],ans:1,hint:"chaqueta = fem. sing. → roja"},
    {q:"un gorro ___ (red)",opts:["rojo","roja","rojos","rojas"],ans:0,hint:"gorro = masc. sing. → rojo"},
    {q:"unas sandalias ___ (red)",opts:["rojo","roja","rojos","rojas"],ans:3,hint:"sandalias = fem. pl. → rojas"},
    {q:"unos pantalones ___ (red)",opts:["rojo","roja","rojos","rojas"],ans:2,hint:"pantalones = masc. pl. → rojos"},
    {q:"una camiseta ___ (green)",opts:["verde","verdes","verdeo","verdea"],ans:0,hint:"verde only changes for plural → verde"},
    {q:"unos zapatos ___ (green)",opts:["verde","verdes","verdeo","verdea"],ans:1,hint:"verde + plural → verdes"},
    {q:"un bolso ___ (orange)",opts:["naranja","naranjoa","naranjos","naranjas"],ans:0,hint:"naranja is invariable → naranja"},
    {q:"unas botas ___ (blue)",opts:["azul","azula","azules","azulos"],ans:2,hint:"azul + plural → azules"},
  ]},
  {topic:"Tener expressions",items:[
    {q:"No he dormido bien. Estoy ___.",opts:["sueño","tengo sueño","hambre","frío"],ans:1,hint:"not slept well → tengo sueño"},
    {q:"¿Comemos? ___ mucha ___.",opts:["Estoy / sueño","Tengo / hambre","Soy / sed","Hay / ganas"],ans:1,hint:"hungry → tengo hambre"},
    {q:"¿Puedo cerrar la ventana? ___ ___.",opts:["Estoy / cansado","Tengo / frío","Soy / sueño","Hay / calor"],ans:1,hint:"cold → tengo frío"},
    {q:"¡___ ___! Has ganado el premio. (lucky)",opts:["Estás / suerte","Tienes / suerte","Eres / suerte","Hay / suerte"],ans:1,hint:"lucky → tienes suerte"},
    {q:"___ que trabajar mañana. (I have to)",opts:["Voy","Quiero","Tengo","Estoy"],ans:2,hint:"obligation = tener que"},
    {q:"¿Cuántos años ___? — Tengo 36. (you have)",opts:["eres","estás","tienes","haces"],ans:2,hint:"age → ¿cuántos años tienes?"},
  ]},
  {topic:"Participles — regular & irregular",items:[
    {q:"hablar →",opts:["hablado","hablido","hablecho","hablato"],ans:0,hint:"-AR → -ado"},
    {q:"comer →",opts:["comado","comido","comecho","comato"],ans:1,hint:"-ER → -ido"},
    {q:"hacer →",opts:["hacido","hacado","hecho","haceto"],ans:2,hint:"irregular → hecho"},
    {q:"ver →",opts:["veido","visto","vido","veado"],ans:1,hint:"irregular → visto"},
    {q:"escribir →",opts:["escribido","escrito","escribado","escribecho"],ans:1,hint:"irregular → escrito"},
    {q:"volver →",opts:["volvido","volvado","vueltado","vuelto"],ans:3,hint:"irregular → vuelto"},
    {q:"decir →",opts:["decido","dicho","decado","diciado"],ans:1,hint:"irregular → dicho"},
    {q:"romper →",opts:["rompido","rompado","roto","rompecho"],ans:2,hint:"irregular → roto"},
  ]},
];
