// Quiz questions
const QUIZ_POOL=[
  {q:"¿Cómo se dice 'I like chocolate'?",inst:"Choose the correct sentence",opts:["Me gusta el chocolate.","Me gustan el chocolate.","Te gusta el chocolate.","Le gusta chocolates."],ans:0},
  {q:"Me ___ los gatos.",inst:"gusta or gustan?",opts:["gusta","gustan","gusto","gustas"],ans:1},
  {q:"___ mesa",inst:"el or la?",opts:["el","la","un","una"],ans:1},
  {q:"___ gato",inst:"el or la?",opts:["la","el","una","los"],ans:1},
  {q:"How do you say 'I have to work'?",inst:"Pick the right translation",opts:["Quiero trabajar","Voy a trabajar","Tengo que trabajar","Trabajo mucho"],ans:2},
  {q:"Voy ___ ir al gimnasio.",inst:"Fill the gap",opts:["de","a","que","para"],ans:1},
  {q:"¿Cuál es el plural de 'el libro'?",inst:"Make it plural",opts:["los libros","las libros","el libros","los libro"],ans:0},
  {q:"How do you say 'Me too' when agreeing with a like?",inst:"Choose the correct phrase",opts:["A mí tampoco","A mí también","A mí no","A mí sí"],ans:1},
  {q:"¿Cómo se dice 'I have two sisters'?",inst:"Choose the right sentence",opts:["Tengo dos hermanas.","Tienes dos hermanas.","He dos hermanas.","Yo dos hermanas."],ans:0},
  {q:"Me ___ vivir en la ciudad.",inst:"verb → gusta or gustan?",opts:["gustan","gusto","gusta","gustas"],ans:2},
  {q:"¿Cómo se dice 'I have just finished work'?",inst:"Use acabo de",opts:["Voy a trabajar.","Acabo de trabajar.","Tengo que trabajar.","Trabajo ahora."],ans:1},
  {q:"Yo ___ en Madrid. (vivir)",inst:"Regular -IR verb",opts:["vivas","vive","vivo","vivemos"],ans:2},
  {q:"How do you say 'I don't like Mondays'?",inst:"Use me gusta/n correctly",opts:["No me gustan los lunes.","No me gusta los lunes.","No te gustan los lunes.","No le gusta el lunes."],ans:0},
  {q:"___ zapato",inst:"el or la?",opts:["la","el","un","una"],ans:1},
  {q:"¿Cómo se dice 'What have you done?'",inst:"Pretérito perfecto",opts:["¿Qué haces?","¿Qué vas a hacer?","¿Qué has hecho?","¿Qué hiciste?"],ans:2},
  {q:"A Brad Pitt ___ gusta Angelina.",inst:"me/te/le/nos?",opts:["me","te","le","les"],ans:2},
  {q:"¿Qué significa '¡Qué asco!'?",inst:"Translate the reaction",opts:["How strange!","How awful!","How disgusting!","How annoying!"],ans:2},
  {q:"¿Cómo se dice 'I'm going to travel to Spain'?",inst:"Use voy a",opts:["Quiero viajar a España.","Voy a viajar a España.","Tengo que viajar a España.","Viajo a España."],ans:1},
  {q:"¿Cuál es el plural de 'la flor'?",inst:"Ends in consonant → add -es",opts:["las floras","los flores","las flores","la flores"],ans:2},
  {q:"'There is a park near my house.' →",inst:"ser, estar or hay?",opts:["Es un parque cerca.","Está un parque cerca.","Hay un parque cerca.","Son parques cerca."],ans:2},
  {q:"'The keys are on the table.' → Las llaves ___ encima de la mesa.",inst:"ser, estar or hay?",opts:["son","hay","estar","están"],ans:3},
  {q:"'I'm happy.' →",inst:"ser or estar?",opts:["Soy feliz.","Estoy feliz.","Hay feliz.","Tengo feliz."],ans:1},
  {q:"'I have gone.' → He ___",inst:"Irregular participle of ir",opts:["ido","voy","ir","va"],ans:0},
  {q:"Nosotros ___ visto una película.",inst:"haber + participle",opts:["hemos","habéis","han","he"],ans:0},
  {q:"¿Has estado en España ___ vez?",inst:"'ever' in Spanish",opts:["alguna","ninguna","cada","otra"],ans:0},
  {q:"'She's wearing a nice dress.' →",inst:"llevar = to wear",opts:["Ella tiene un vestido bonito.","Ella lleva un vestido bonito.","Ella está un vestido bonito.","Ella pone un vestido bonito."],ans:1},
  {q:"'I'm from Ireland.' →",inst:"Use soy de",opts:["Estoy de Irlanda.","Hay Irlanda.","Soy de Irlanda.","Tengo Irlanda."],ans:2},
  {q:"¿Qué significa 'Pues, resulta que...'?",inst:"Translate the expression",opts:["Well, I think that...","Well, it turns out that...","Well, the thing is...","By the way..."],ans:1},
  {q:"'I like your shoes!' → ¡Me ___ mucho tus zapatos!",inst:"gusta or gustan?",opts:["gusta","gustan","gusto","gustas"],ans:1},
  {q:"¿Cuántos años ___ ? (you have)",inst:"tener — tú form",opts:["eres","estás","tienes","haces"],ans:2},
];

